sudo: required

language: ruby

services:
  - docker

branches:
  only:
    - master
    
before_script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
- docker build -t dmonter/mugre-bot:latest .
- docker push dmonter/mugre-bot:latest
